version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/expense_tracker

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Lint JavaScript code
          command: npm run lint

  yaml_lint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install YAMLlint
          command: |
            sudo apt-get update
            sudo apt-get install -y npm
            sudo npm install -g yaml-lint
      - run:
          name: Lint YAML files
          command: |
            yaml-lint **/*.yaml || true

  gitleaks:
    docker:
      - image: zricethezav/gitleaks:v8.3.0
    steps:
      - checkout
      - run:
          name: Run Gitleaks
          command: |
            gitleaks detect --source . --report-format json --report-path gitleaks-report.json
            cat gitleaks-report.json

  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install dependencies
          command: |
            echo '{"dependencies": {"express": "4.0.0"}}' > package.json
            npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Check for vulnerabilities
          command: npm audit --production

  terraform:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
            unzip terraform_1.5.0_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform --version
      - run:
          name: Load environment variables from .env file
          command: |
            export $(grep -v '^#' .env | xargs)
      - run:
          name: Terraform init
          command: terraform init
          working_directory: infrastructure/
      - run:
          name: Terraform plan
          command: terraform plan -var="aws_access_key=$AWS_ACCESS_KEY_ID" -var="aws_secret_key=$AWS_SECRET_ACCESS_KEY" -var="db_password=$DB_PASSWORD" -var="s3_bucket_name=$S3_BUCKET_NAME"
          working_directory: infrastructure/
      - run:
          name: Terraform apply (development)
          command: terraform apply -auto-approve -var="aws_access_key=$AWS_ACCESS_KEY_ID" -var="aws_secret_key=$AWS_SECRET_ACCESS_KEY" -var="db_password=$DB_PASSWORD" -var="s3_bucket_name=$S3_BUCKET_NAME"
          working_directory: infrastructure/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - lint
      - yaml_lint:
          requires:
            - lint
      - gitleaks:
          requires:
            - yaml_lint
      - build:
          requires:
            - gitleaks
      - terraform:
          requires:
            - build
